### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by augustinejenin** [jasonjoh/git-the-gist#2]
It shows "sample not working error" when i installed in outlooks add-in

**Comment by jasonjoh** [comment]
I'm sorry to hear that. The README has instructions on getting this working. If you're doing all of that and it still doesn't work, please provide more detail.

**Comment by rajat-np** [comment]
Can this add-in be side-loaded in outlook webapp?

**Comment by jasonjoh** [comment]
@rajat-np yes, of course.

@augustinejenin since it's been a while, I'm going to close this. Feel free to reopen if you are still having a problem.
